import Head from 'next/head'
import { FC, ReactNode } from 'react'
import { AppShell } from '@mantine/core'
import HeaderCustom from './HeaderCustom'
import FooterCustom from './FooterCustom'

//ページのタイトルとchildren
type Props = {
  title: string
  children: ReactNode
}
//全てのページで共通して使えるレイアウトを作成
//デフォルトのタイトルは'Home'に設定
export const Layout: FC<Props> = ({ children, title = 'Home' }) => {
  return (
    <AppShell
      padding="md"
      header={<HeaderCustom mode={title} />}
      footer={<FooterCustom />}
      styles={(theme) => ({
        main: {
          backgroundColor:
            title !== 'Home'
              ? theme.colorScheme === 'dark'
                ? theme.colors.dark[8]
                : theme.colors['custom-blue'][0]
              : theme.colorScheme === 'dark'
              ? theme.colors.dark[8]
              : theme.colors.white,
        },
      })}
    >
      <div className="flex min-h-screen flex-col items-center justify-center">
        <Head>
          <title>{title}</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="flex w-screen flex-1 flex-col items-center justify-center">
          {children}
        </main>
      </div>
    </AppShell>
  )
}
