//全てのページで共通して使えるレイアウトを作成する

//FC: ファンクショナルコンポーネントの型
//ReactNode: childrenの型
import Head from 'next/head'
import { FC, ReactNode } from 'react'

import { AppShell } from '@mantine/core'
import HeaderCustom from './HeaderCustom'
import FooterCustom from './FooterCustom'

//Layoutコンポーネントが受け取るpropsの型を定義(ページのタイトルとchildrenを受け取る)
type Props = {
  title: string
  children: ReactNode
}
//FC<Props>で型を適用
//デフォルトのタイトルは'Nextjs'に設定
export const Layout: FC<Props> = ({ children, title = 'Home' }) => {
  return (
    <AppShell
      padding="md"
      header={<HeaderCustom mode={title} />}
      footer={<FooterCustom />}
      styles={(theme) => ({
        main: {
          backgroundColor:
            theme.colorScheme === 'dark'
              ? theme.colors.dark[8]
              : theme.colors.gray[0],
        },
      })}
    >
      <div className="flex min-h-screen flex-col items-center justify-center">
        <Head>
          <title>{title}</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="flex w-screen flex-1 flex-col items-center justify-center">
          {children}
        </main>
      </div>
    </AppShell>
  )
}
